### ISSUE TITLE
Possession

### ISSUE THREAD

**Issue by parrajeremy** [sealneaward/nba-movement-data#1]
Thank you for making this data easy to get to. Is there a straight forward way to get at "got" and "lost" possession events?

**Comment by sealneaward** [comment]
@parrajeremy those would be turnover events, which are easily accessible through the NBA Stats api.

**Comment by parrajeremy** [comment]
Thanks for the quick response. I should have been more clear. I am looking to identify possession, i.e. identify the ball handler for the duration of the possession. I see that I can try to infer this from the event sequence. I am more likely to build a state model using some observables (e.g. proximity to the ball, relative velocity, etc.) Was thinking that maybe this had already been done.
